language: node_js
node_js:
  - "8"
  - "7.8"
script: npm run lint && npm run test-on-travis
after_success:
  - npm install codeclimate-test-reporter && codeclimate-test-reporter < ./coverage/lcov.info
